#!/bin/bash
# /etc/init.d/buttonmon

### BEGIN INIT INFO
# Provides:          buttonmon
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example initscript
# Description:       This service is used to manage a python GPIO button daemon 
### END INIT INFO


case "$1" in 
    start)
        echo "Starting buttonmon"
        /home/pi/servoblaster/PiBits/ServoBlaster/user/servo
        ;;
    stop)
        echo "Stopping buttonmon"
        killall buttonmon
        ;;
    *)
        echo "Usage: /etc/init.d/servod start|stop"
        exit 1
        ;;
esac

exit 0
