#!/bin/bash
# /etc/init.d/buttonmon

### BEGIN INIT INFO
# Provides:          buttonmon
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example initscript
# Description:       This service is used to manage a python GPIO button daemon 
### END INIT INFO


case "$1" in 
    start)
        runningps=$(ps aux | grep button.py | grep -v grep);
        if [[ -n $runningps ]]; then
            echo "Already running"
            exit 1; 
        fi
        echo "Starting buttonmon"
        /home/bojung1/dev/TestRig/button.py &
        ;;
    stop)
        echo "Stopping buttonmon"
        pkill -f button.py;
        pkill -f startpar;
        ;;
    *)
        echo "Usage: /etc/init.d/buttonmon start|stop"
        exit 1
        ;;
esac

exit 0
