#!/bin/bash
# /etc/init.d/zombiemon



### BEGIN INIT INFO
# Provides:          zombiemon
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example initscript
# Description:       the janky zombie autorig killer  
### END INIT INFO


case "$1" in 
    start)
        runningps=$(ps aux | grep zombie.py | grep -v grep);
        if [[ -n $runningps ]]; then
            echo "Already running"
            exit 1; 
        fi
        echo "Starting zombiemon"
        /home/bojung1/dev/TestRig/zombie.py &
        ;;
    stop)
        echo "Stopping zombiemon"
        pkill -f zombie.py;
        ;;
    *)
        echo "Usage: /etc/init.d/zombiemon start|stop"
        exit 1
        ;;
esac

exit 0
